icons = "material-nf"
theme = "horizon"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%d.%m.%y %I:%M%P"
