# vim: ft=tmux
# --- Kanso Palette ---
# Background: #090E13
# Foreground: #C5C9C7
# Selection/Active: #E6C384 (Bright Yellow)
# Inactive/Dark: #22262D
# Accent/Blue: #7FB4CA
# Muted/Grey: #A4A7A4

set -g mode-style "fg=#090E13,bg=#E6C384"

set -g message-style "fg=#C5C9C7,bg=#22262D"
set -g message-command-style "fg=#C5C9C7,bg=#22262D"

set -g pane-border-style "fg=#22262D"
set -g pane-active-border-style "fg=#7FB4CA"

set -g status "on"
set -g status-interval 1
set -g status-justify "left"

set -g status-style "fg=#A4A7A4,bg=#090E13"

set -g status-bg "#090E13"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#[fg=#090E13,bg=#C5C9C7,bold] #S #[fg=#C5C9C7,bg=#090E13,nobold,nounderscore,noitalics]"

set -g status-right "#[fg=#22262D,bg=#090E13,nobold,nounderscore,noitalics]#[fg=#A4A7A4,bg=#22262D]#[fg=#22262D,bg=#22262D,nobold,nounderscore,noitalics]#[fg=#C5C9C7,bg=#22262D]#[fg=#7FB4CA,bg=#22262D,nobold,nounderscore,noitalics]#[fg=#090E13,bg=#7FB4CA,bold] #h "

setw -g window-status-activity-style "underscore,fg=#A4A7A4,bg=#090E13"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#A4A7A4,bg=#090E13"

setw -g window-status-format '#[fg=#090E13,bg=#090E13]#[default] #I  #{b:pane_current_path} #[fg=#090E13,bg=#090E13,nobold,nounderscore,noitalics]'

setw -g window-status-current-format '#[fg=#090E13,bg=#C5C9C7]#[fg=#090E13,bg=#C5C9C7] #I #[fg=#090E13,bg=#C5C9C7] #[fg=#090E13]#{b:pane_current_path} #[fg=#C5C9C7,bg=#090E13,nobold]'
