set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# rebind action key
unbind C-b
set-option -g prefix C-t
set-option -g repeat-time 0
set-option -g focus-events on

# change base index
set -g base-index 1

# switch windows
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

# enable vi mode
setw -g mode-keys vi

# reload config
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# delete current pane
bind -r e kill-pane -a

# title bar
set -g set-titles on
set -g set-titles-string "#T"

set-option -g history-limit 64096
set -sg escape-time 10

# statusline
source ~/.config/tmux/statusline.conf

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

# load tpm
run '~/.tmux/plugins/tpm/tpm'
