set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# rebind action key
unbind C-b
set-option -g prefix C-t
set-option -g repeat-time 0
set-option -g focus-events on

# switch windows
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

# enable vi mode
set-window-option -g mode-keys vi

# reload config
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# open current directory
bind o run-shell "xdg-open '#{pane_current_path}"
bind -r e kill-pane -a

# title bar
set -g set-titles on
set -g set-titles-string "#T"

# colors
set-option -g status-fg cyan
set-option -g status-bg black
set -g pane-active-border-style fg=colour166,bg=default
set -g window-style fg=colour10,bg=default
set -g window-active-style fg=colour12,bg=default
set-option -g history-limit 64096
set -sg escape-time 10

source ~/.config/tmux/statusline.conf
