;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #1a1c23
background-alt = #2E303E
foreground = #E7E7E7
primary = #FFFFFF
secondary = #808080
alert = #A54242
disabled = #707880

[bar/zero]
width = 100%
height = 24pt
radius = 0

enable-ipc = true
dpi = 76
padding = 1
module-margin = 1

background = ${colors.background}
foreground = ${colors.foreground}

border-top-size = 3
border-top-color = #2E303E

line-size = 2

tray-position = center

border-size = 0pt
border-color = #00000000
fixed-center = true

separator = /
separator-foreground = ${colors.secondary}

font-0 = JetBrains Mono Nerd Font;1

modules-left = launcher workspaces xwindow
modules-right = pulseaudio cpu memory time date powermenu
modules-center = 

cursor-click = pointer
cursor-scroll = ns-resize

[module/workspaces]
type = internal/xworkspaces

icon-0 = "1;"
icon-1 = "2;"
icon-2 = "3;"
icon-3 = "4;"
icon-default = 

format = <label-state> <label-mode>

label-active = %icon%
label-active-background = ${colors.background-alt}
label-active-underline= #E95678
label-active-padding = 1

label-occupied = %icon%
label-occupied-padding = 1

label-urgent = %icon%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %icon%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/launcher]
type = custom/text
content = 

content-background = ${color.primary}
content-foreground = ${color.foreground}
content-padding = 1

click-left = /home/zero/.config/rofi/launchers/colorful/launcher.sh &

[module/powermenu]
type = custom/text
content = 

content-background = ${color.primary}
content-foreground = ${color.foreground}
content-padding = 1

click-left = /home/zero/.config/rofi/applets/android/powermenu.sh &

[module/cpu]
type = internal/cpu

format-prefix = " "
format-prefix-underline = #29D398

label = %percentage%%
label-underline = #29D398

interval = 1

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = " "
format-volume-underline = #59E3E3
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

tray-position = center

label-volume = %percentage%%
label-volume-underline = #59E3E3

label-muted = muted
label-muted-foreground = ${colors.disabled}
label-muted-underline = #59E3E3

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label = %layout%
label-underline = #29D398

format-prefix = " "
format-prefix-underline = #29D398
format-prefix-foreground = ${colors.primary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-underline = #EE64AE
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%
label-underline = #EE64AE

[module/time]
type = internal/date
interval = 1

format-prefix = " "
format-prefix-underline = #E95678
format-prefix-foreground = ${colors.primary}

date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S

label = %date%
label-underline = #E95678

[module/date]
type = internal/date
interval = 1

format-prefix = " "
format-prefix-underline = #FAB795
format-prefix-foreground = ${colors.primary}

date = %d.%m.%Y

label = %date%
label-underline = #FAB795

[settings]
throttle-output = 5
throttle-output-for = 10
screenchange-reload = false
compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over
pseudo-transparency = false

; vim:ft=dosini
